# -*- coding: utf-8 -*-
"""Thesis prototype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgfC4t0XHJOsb4UqhKN1_hJgZzGCGkD_
"""

import pandas as pd

# Load files
candidate_df = pd.read_csv("candidate_skills.csv")
role_df = pd.read_csv("role_requirements.csv")

# Merge candidate skills with role requirements
data = candidate_df.merge(
    role_df,
    on=["role_id", "skill_name"],
    how="outer"
)

# Fill missing skill levels with 0
data["skill_level"] = data["skill_level"].fillna(0)
data["required_level"] = data["required_level"].fillna(0)

# Calculate skill gap
data["skill_gap"] = data["required_level"] - data["skill_level"]

# Add a new column for skill gap interpretation
def display_skill_gap_value(gap):
    if gap < 0:
        return "Exceeds Requirement"
    elif gap == 0:
        return "No Gap"
    elif gap > 0:
        return "Deficit"

data["interpretation"] = data["skill_gap"].apply(display_skill_gap_value)

# Define intervention logic
def intervention_rule(gap):
    if gap >= 2:
        return "Formal training required"
    elif gap == 1:
        return "On-the-job coaching recommended"
    elif gap == 0:
        return "No intervention needed"
    elif gap < 0:
        return "Early autonomy"

data["onboarding_intervention"] = data["skill_gap"].apply(intervention_rule)

# Order by role_id and candidate_id
data = data.sort_values(by=['role_id', 'candidate_id']).reset_index(drop=True)

# Write csv file
data.to_csv("Personalized Onboarding.csv", index=False)

print("CSV files created!")
